// Auth
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';

// User
export const GET_USER_SUMMARY = 'GET_USER_SUMMARY';
export const GET_USER_BALANCE_SUMMARY = 'GET_USER_BALANCE_SUMMARY';
export const GET_USER_REFER = 'GET_USER_REFER';

// Activity
export const GET_SIGN_INFO = 'GET_SIGN_INFO';
export const GET_BGP_PRODUCTS = 'GET_BGP_PRODUCTS';
export const GET_BGP_PRODUCT_DETAIL = 'GET_BGP_PRODUCT_DETAIL';
export const GET_BGP_TRANSFER_DETAILS = 'GET_BGP_TRANSFER_DETAILS';
export const GET_BGP_TRANSFER_HISTORY = 'GET_BGP_TRANSFER_HISTORY';
export const GET_BANNER_LIST = 'GET_BANNER_LIST';
export const GET_USER_IS_SIGN_IN = 'GET_USER_IS_SIGN_IN';
export const GET_BGP_RECORD = 'GET_BGP_RECORD';
export const GET_BGP_DETAIL_LIST = 'GET_BGP_DETAIL_LIST';
export const GET_ADDRESS_DETAIL = 'GET_ADDRESS_DETAIL';
export const GET_PRODUCT_BUY_RESULT = 'GET_PRODUCT_BUY_RESULT';

// 交易大赛
export const GET_TEAM_DETAIL = 'GET_TEAM_DETAIL';
export const GET_HOME_DATA = 'GET_HOME_DATA';
export const GET_HOME_COMMENTS = 'GET_HOME_COMMENTS';
export const GET_HOME_REPORTS = 'GET_HOME_REPORTS';
export const GET_HOME_TOP1 = 'GET_HOME_TOP1';
export const GET_RANK_LIST = 'GET_RANK_LIST';

// 二期
export const GET_RACE_HOME = 'GET_RACE_HOME';
export const GET_RACE_RANKING_LIST = 'GET_RACE_RANKING_LIST'; // 二期结束
export const GET_RACE_DETAIL = 'GET_RACE_DETAIL';
