// Auth
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';

// User
export const GET_USER_SUMMARY = 'GET_USER_SUMMARY';
export const GET_USER_BALANCE_SUMMARY = 'GET_USER_BALANCE_SUMMARY';

// Activity
export const GET_SIGN_INFO = 'GET_SIGN_INFO';
export const GET_BGP_PRODUCTS = 'GET_BGP_PRODUCTS';
export const GET_BGP_PRODUCT_DETAIL = 'GET_BGP_PRODUCT_DETAIL';
export const GET_BGP_TRANSFER_DETAILS = 'GET_BGP_TRANSFER_DETAILS';
export const GET_BGP_TRANSFER_HISTORY = 'GET_BGP_TRANSFER_HISTORY';
