const countries = [
  {
    key: 'China',
    text: '中国',
    value: '+86',
    label: '+86',
  },
  {
    key: 'Hongkong',
    text: '香港(中国)',
    value: '+852',
    label: '+852',
  },
  {
    key: 'Taiwan',
    text: '台湾(中国)',
    value: '+886',
    label: '+886',
  },
  {
    key: 'Korea',
    text: '韩国',
    value: '+82',
    label: '+82',
  },
  {
    key: 'United States of America',
    text: '美国',
    value: '+1',
    label: '+1',
  },
  {
    key: 'United Kiongdom',
    text: '英国',
    value: '+44',
    label: '+44',
  },
  {
    key: 'Canada',
    text: '加拿大',
    value: '+1',
    label: '+1',
  },
  {
    key: 'The United Arab Emirates',
    text: '阿联酋',
    value: '+971',
    label: '+971',
  },
  {
    key: 'Australia',
    text: '澳大利亚',
    value: '+61',
    label: '+61',
  },
  {
    key: 'Austria',
    text: '奥地利',
    value: '+43',
    label: '+43',
  },
  {
    key: 'Pakistan',
    text: '巴基斯坦',
    value: '+92',
    label: '+92',
  },
  {
    key: 'Bulgaria',
    text: '保加利亚',
    value: '+359',
    label: '+359',
  },
  {
    key: 'Germany',
    text: '德国',
    value: '+49',
    label: '+49',
  },
  {
    key: 'Russia',
    text: '俄罗斯',
    value: '+7',
    label: '+7',
  },
  {
    key: 'Philippines',
    text: '菲律宾',
    value: '+63',
    label: '+63',
  },
  {
    key: 'Georgia',
    text: '格鲁吉亚',
    value: '+995',
    label: '+995',
  },
  {
    key: 'Netherlands',
    text: '荷兰',
    value: '+31',
    label: '+31',
  },
  {
    key: 'Ghana',
    text: '加纳',
    value: '+233',
    label: '+233',
  },
  {
    key: 'Latvia',
    text: '拉托维亚',
    value: '+371',
    label: '+371',
  },
  {
    key: 'Lithuania',
    text: '立陶宛',
    value: '+370',
    label: '+370',
  },
  {
    key: 'Malaysia',
    text: '马来西亚',
    value: '+60',
    label: '+60',
  },
  {
    key: 'South Africa',
    text: '南非',
    value: '+27',
    label: '+27',
  },
  {
    key: 'Nigeria',
    text: '尼日利亚',
    value: '+234',
    label: '+234',
  },
  {
    key: 'Switzerland',
    text: '瑞士',
    value: '+41',
    label: '+41',
  },
  {
    key: 'Slovenia',
    text: '斯洛文尼亚',
    value: '+386',
    label: '+386',
  },
  {
    key: 'Venezuela',
    text: '委内瑞拉',
    value: '+58',
    label: '+58',
  },
  {
    key: 'Singapore',
    text: '新加坡',
    value: '+65',
    label: '+65',
  },
  {
    key: 'New Zealand',
    text: '新西兰',
    value: '+64',
    label: '+64',
  },
  {
    key: 'Iran',
    text: '伊朗',
    value: '+98',
    label: '+98',
  },
  {
    key: 'Israel',
    text: '以色列',
    value: '+972',
    label: '+972',
  },
];

export default countries;
